# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drug-model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drug-api
  template:
    metadata:
      labels:
        app: drug-api
    spec:
      containers:
      - name: drug-api
        image: bijuthottathil/drug-api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: drug-api-service
spec:
  selector:
    app: drug-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
